version: '2'
# list out all the services that are running
services:
  # name of the container
  app:
    extends:
      # this container is an extension from the service name "app" in the 
      # "docker-compose.common.yml" in the "docker" folder
      # extend files to keep things separate and clear
      # "extends" is not needed to run docker-compose, but it is a good practice to have it
      file: docker/docker-compose.common.yml
      service: app
    # map port 8000 in host to port 8000 in container so when you start the python web
    # application inside the container at port 8000 (by running
    # "python manage.py runserver 0.0.0.0:8000" command in "scripts/start_app.sh", you can
    # access the web application from the browser in the host at port 8000 (by typing in
    # "localhost:8000" in the browser)
    ports:
      - 8000:8000
    # mount everything in the host system into the container in real time so all the files in
    # the container always synchronize to the files in the host system without having to do
    # "docker-compose build" each time after made changes to the files
    volumes:
      - .:/usr/src/app/
